Lab2
sergey-berezin/402_semenov pull request #3
Opened 2022-10-28 18:12 UTC by Well1306

2022-11-01 08:49 UTC, sergey-berezin requested changes

2022-11-01 08:49 UTC, sergey-berezin commented on Emotions_2/MainWindow.xaml.cs
> +                        var res = await a.Emotions(inputs, token);
Надо защититься от повторного входа.

2022-11-01 08:49 UTC, sergey-berezin commented on Emotions_2/MainWindow.xaml
> +                        <TextBlock Text="{Binding Name}"/>
Надо отобразить картинку, а не имя файла

2022-11-05 20:51 UTC, sergey-berezin requested changes
Папка .vs лишняя и включена в PR по ошибке.

2022-11-06 14:51 UTC, Well1306 commented
удалил

2022-11-08 07:54 UTC, merged