Lab3
sergey-berezin/402_semenov pull request #4
Opened 2022-11-17 18:07 UTC by Well1306

Чтобы удалить картинку из БД ПКМ на нее -> drop

2022-12-02 07:47 UTC, sergey-berezin requested changes

2022-12-02 07:47 UTC, sergey-berezin commented on Emotions_3/MainWindow.xaml.cs
> +                            Interlocked.Increment(ref count);
Зачем нужен именно `Interlocked`? Почему не просто `++`?

2022-12-02 07:47 UTC, sergey-berezin commented on Emotions_3/MainWindow.xaml.cs
> +                        catch (Exception ex) { MessageBox.Show("Calculation Canceled"); break; }
При отмене вычислений возникает исключение `OperationCancelledException`. Ловить надо именно его. Иначе сообщение об отмене вычислений будут выдаваться при любой ошибке.

2022-12-02 07:47 UTC, sergey-berezin commented on Emotions_3/MainWindow.xaml.cs
> +                    var q = db.Pic.Where(x => x.Hash == hash);
1) Можно добавить `.First()`, тогда запрос в БД будет выполняться до первого найденного хэша.
2) В случае совпадения хэшей надо дополнительно сравнить содержимое файлов (требования задания 3).

2022-12-02 14:56 UTC, Well1306 commented on Emotions_3/MainWindow.xaml.cs
> +                    var q = db.Pic.Where(x => x.Hash == hash);
если добавить .First(), то появляется исключение sequence has no elements, поэтому оставил как есть

2022-12-02 14:57 UTC, Well1306 commented on Emotions_3/MainWindow.xaml.cs
> +                        catch (Exception ex) { MessageBox.Show("Calculation Canceled"); break; }
поправил

2022-12-02 14:57 UTC, Well1306 commented on Emotions_3/MainWindow.xaml.cs
> +                            Interlocked.Increment(ref count);
поправил

2022-12-07 15:35 UTC, Well1306 commented on Emotions_3/MainWindow.xaml.cs
> +                    var q = db.Pic.Where(x => x.Hash == hash);
добавил FirstOrDefault()

2022-12-09 07:18 UTC, merged